# -*- coding: utf-8 -*-
"""Trabajo_primera_clase_modelamiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L61WGsmvq4MQvGSShHBp4SK87gJdx5Ph
"""

#Importar las librerias
import numpy as np #Permite las operaciones matematicas np.
import matplotlib.pyplot as plt #Permite graficar

"""En esta celda se importan las librerias necesarias para el codigo con el que se va a trabajar."""

# Parametros generales
k = 0.1 #Constante de velocidad (1/s) #Constante cinetica de degradación de

#Función del reactor Batch
#Ecuaciones: d[A]/dt = -k[A], d[B]/dt = k[A]
def batch_reactor (t, A0): #Función que describe el reactor Batch
  A = A0*np.exp(-k*t) #Concentración de A en función del tiempo
  B = A0*(1-np.exp(-k*t)) #Concentración de B en función del tiempo
  return A, B

#Reactor de flujo Pistón (PFR)
#Ecuaciones: d[A]/dx = -k[A]/v, d[B]/dx = k[A]/v
def pfr_reactor(x, A0, v): #Función que describe el reactor flujo pistón
  A = A0*np.exp(-k*x/v) #Concentración de A en función de la posición
  B = A0*(1-np.exp(-k*x/v)) #Concentración de B en función de la posición
  return A, B

#Modelado de los reactores
#imponer las condiciones iniciales y de contorno, en otras palabras tiempo y posición
time = np.linspace(0, 50, 500) #Tiempo para el reactor Batch (s), paso del tiempo (Inicio, paso, final)
position = np.linspace(0, 50, 500) # Posición para el PFR (m), x paso de posición (Inicio, paso, final)
A0 = 1.0 #Concentración inicial de A (mol/L), La concentración inicial de la sustancia que se va a tener
v = 1.0 #Velocidad de flujo en el PFR (m/s), velocidad de flujo que tiene R. F. P.

#Obtener concentraciones para ambos reactores
A_batch, B_batch = batch_reactor(time, A0) # Concentración final Reactor Batch
A_pfr, B_pfr = pfr_reactor(position, A0, v) # Concentración final de R. F.P. Reactor PFR

#Graficas
plt.figure(figsize=(14, 6)) #Tamaño de la figura

#Grafica para el reactor Batch
plt.subplot(1, 2, 1)
plt.plot(time, A_batch, label='[A] (Batch)', color='blue')
plt.plot(time, B_batch, label='[B] (Batch)', color='green')
plt.xlabel('Tiempo (s)')
plt.ylabel('Concentración (mol/L)')
plt.title('Reactor Batch')
plt.legend()

#Grafica del reactor PFR
plt.subplot(1, 2, 2)
plt.plot(position, A_pfr, label='[A] (PFR)', color='blue')
plt.plot(position, B_pfr, label='[B] (PFR)', color='green')
plt.xlabel('Posición (m)')
plt.ylabel('Concentración (mol/L)')
plt.title('Reactor de Flujo Pistón: Concentración vs. Posición')
plt.legend()

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

#Parametros generales
k_fermentación = 0.05
k_degradación = 0.01

#Reactor Batch Natural: ______________
# Ecuaciones: d[Azúcar]/dt = -k[Azúcar], d[Alcohol]/dt = k[Azúcar]
def fermentación_batch(t, Azucar0):
  Azucar = Azucar0 * np.exp(-k_fermentación * t) #Concentración de azúcar en función del tiempo
  Alcohol = Azucar0 * (1 - np.exp(-k_fermentación * t)) #Concentración de alcohol en función del tiempo
  return Azucar, Alcohol

  #Reactor PFR natural:_________________________
# Ecuaciones: d[Contaminante]/dx = -k[contaminante]/v, d[producto]/dx = k[Contaminante]/v
def degradación_pfr(x, Contaminante0, v):
  Contaminante = Contaminante0 * np.exp(-k_degradación * x / v) #Concentración de contaminante en función de la posición
  producto = Contaminante0 * (1 - np.exp(-k_degradación * x / v)) #Concentración de producto en función de la posición
  return Contaminante, producto

  #Modelado---
  # Tiempo para fermentación (días) y posición para el flujo del agua (metros)
time_fermentación = np.linspace(0, 100, 500) #Tiempo (días)position_agua = np.linspace(0, 100, 500) #Posición (metros)
position_agua = np.linspace(0, 100, 500) #Posición (metros)
  #Simulación para diferentes concentraciones iniciales y velocidades
Azucar0_list = [5.0, 10.0, 15.0] # Diferentes concentraciones iniciales de azúcar (g/L)
Contaminante0_list = [2.0, 5.0, 8.0] #Diferentes concentraciones iniciales de contaminante (mg/L)
v_agua_list = [0.3, 0.5, 0.7] #Diferentes velocidades de flujo (m/día)

  # Aguas separadas para la fermentación (Reactor Batch natural
for Azucar0 in Azucar0_list:
    Azucar_batch, Alcohol_batch = fermentación_batch(time_fermentación, Azucar0)
    plt.figure(figsize=(8, 6))
    plt.plot(time_fermentación, Azucar_batch, label=f'[Azúcar] (Batch) Azucar0={Azucar0} g/L', color='orange')
    plt.plot(time_fermentación, Alcohol_batch, label=f'[Alcohol] (Batch) Azucar0={Azucar0} g/L', color='red')
    plt.xlabel('Tiempo (días)')
    plt.ylabel('Concentración (g/L)')
    plt.title(f'Fermentación de uvas: Concentración vs. Tiempo (Azucar0={Azucar0} g/L)')
    plt.legend()
    plt.grid(True)
    plt.show()

  # Graficas separadas para la degradación de contaminantes (PFR natural)
for Contaminante0 in Contaminante0_list:
  for v_agua in v_agua_list:
    Contaminante_pfr, Producto_pfr = degradación_pfr(position_agua, Contaminante0, v_agua)
    plt.figure(figsize=(8, 6))
    plt.plot(position_agua, Contaminante_pfr, label=f'[Contaminante] (PFR) Contaminante0={Contaminante0} mg/L, v={v_agua} m/día', color='blue')
    plt.plot(position_agua, Producto_pfr, label=f'[Producto] (PFR) Contaminante0={Contaminante0} mg/L, v={v_agua} m/día', color='green')
    plt.title (f'Degradación de contaminantes: Concentración vs. Posición\n(Contaminante0={Contaminante0} mg/L, v={v_agua}m/día)')
    plt.xlabel('Posición (m)')
    plt.ylabel('Concentración (mg/L)')
    plt.legend()
    plt.grid(True)
    plt.show()

"""-Fermentación de los Encurtidos:
  En el encurtido de pepinos, bacterias fermentativas convierten los azúcares naturales de los pepinos en ácido láctico. Este proceso es similar al del chucrut, ya que el ácido láctico es el principal producto que conserva los encurtidos y les da un sabor ácido.

  En este caso, los azúcares del pepino disminuyen a medida que se forman ácido láctico y otros compuestos.

-Fermentación del Cacao para Chocolate:
  Las semillas de cacao se fermentan para desarrollar los sabores que son esenciales para el chocolate. Durante la fermentación, las levaduras y bacterias convierten los azúcares en los granos de cacao en alcohol, ácido láctico y ácido acético.

  Aquí, los azúcares en las semillas de cacao disminuyen, mientras que el ácido acético y otros ácidos orgánicos aumentan, lo que contribuye al desarrollo del sabor en el chocolate.

"""